import {writeFile} from 'node:fs/promises';
const modules=['core','operators','advanced','lifecycle','extras','helpers','kernel','compatibility'];
const locations=new Map();
for(const module of modules){const exports=await import(`../src/${module}.js`);for(const [key,value]of Object.entries(exports))locations.set(key,{module,value});}
const identifiers=new Set(locations.keys());
let out='// Public ESM entry point. Generated by scripts/generate-index.mjs.\n';
for(const module of modules){const names=[...locations].filter(([,v])=>v.module===module).map(([k])=>k);out+=`export { ${names.join(', ')} } from './${module}.js';\n`;}
const registry=[];
for(const [name,{module,value}]of locations){if(typeof value!=='function'||!/^[a-z]/.test(name)||['fluent','installFluentOperators','setObservableDecorator','snapshotChanges','applyChanges'].includes(name))continue;let upper=name[0].toUpperCase()+name.slice(1);if(name==='switchLatest')upper='Switch';if(!identifiers.has(upper)){identifiers.add(upper);out+=`export { ${name} as ${upper} } from './${module}.js';\n`;}if(!registry.some(([alias])=>alias===upper))registry.push([upper,name,module]);}
for(const [alias,name,module]of registry)out+=`import { ${name} as op${alias} } from './${module}.js';\n`;
out+=`import { installFluentOperators } from './compatibility.js';\ninstallFluentOperators({${registry.map(([alias])=>`${alias}:op${alias}`).join(',')}});\n`;
await writeFile('src/index.js',out);
console.log(`${locations.size} primary exports; ${registry.length} Pascal aliases.`);
